require "simplecov"
SimpleCov.start
require "Minitest/autorun"
require "Minitest/pride"
require "mocha/minitest"
require "./lib/controller"
require "./lib/translator"
require "./lib/writer_manager"
require "./lib/braille_row"
require "./lib/night_reader"
